name: alae_env
dependencies:
- python>=3.6
- pip
- pip :
  - packaging
  - imageio
  - numpy
  - scipy
  - tqdm
  - dlutils
  - bimpy >= 0.1.1
  - dareblopy >= 0.0.5
  - torch >= 1.3
  - torchvision
  - sklearn
  - yacs
  - matplotlib